//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myHealthAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accDoctor
    {
        public int doctorID { get; set; }
        public int hospitalID { get; set; }
        public string doctorsName { get; set; }
        public string specialization { get; set; }
    
        public virtual AccreditedHospital AccreditedHospital { get; set; }
    }
}
