//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myHealthAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccreditedHospital
    {
        public int hospital_id { get; set; }
        public string healthProvider { get; set; }
        public string hospital_name { get; set; }
        public string hospital_address { get; set; }
    }
}
