//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myHealthAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBenefit
    {
        public int rowID { get; set; }
        public int hmoID { get; set; }
        public string benefitsName { get; set; }
        public Nullable<int> amountCovered { get; set; }
    
        public virtual HMO HMO { get; set; }
    }
}
