//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myHealthAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.processings = new HashSet<processing>();
            this.Records = new HashSet<Record>();
        }
    
        public int id { get; set; }
        public int HMO_id { get; set; }
        public string name { get; set; }
        public string position { get; set; }
        public string department { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public int usergroup_id { get; set; }
        public Nullable<int> Contact { get; set; }
        public Nullable<int> IsMarried { get; set; }
        public Nullable<int> Dependents { get; set; }
        public string healthProvider { get; set; }
        public Nullable<int> withPayable { get; set; }
        public Nullable<System.DateTime> Card_Expiration_Date { get; set; }
    
        public virtual HMO HMO { get; set; }
        public virtual usergroup usergroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processing> processings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
    }
}
