//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myHealthAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myhealthDbEntities : DbContext
    {
        public myhealthDbEntities()
            : base("name=myhealthDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accDoctor> accDoctors { get; set; }
        public virtual DbSet<AccreditedHospital> AccreditedHospitals { get; set; }
        public virtual DbSet<EmployeeBenefit> EmployeeBenefits { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<HMO> HMOes { get; set; }
        public virtual DbSet<processing> processings { get; set; }
        public virtual DbSet<requirement> requirements { get; set; }
        public virtual DbSet<usergroup> usergroups { get; set; }
    }
}
