//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myHealthAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class processing
    {
        public int ProcessId { get; set; }
        public int employeeId { get; set; }
        public Nullable<float> balance { get; set; }
        public System.DateTime date { get; set; }
        public string process_type { get; set; }
        public string data { get; set; }
        public string care_of { get; set; }
        public Nullable<int> duration { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
