//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myHealthAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int id { get; set; }
        public string Availment_Claim { get; set; }
        public string Health_Card { get; set; }
        public string Hospital { get; set; }
        public int Covered_Bill { get; set; }
        public string Date { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
