//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myHealthAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reqAssessment
    {
        public int id { get; set; }
        public int form { get; set; }
        public int TIN { get; set; }
        public int medical { get; set; }
        public int NSO { get; set; }
        public Nullable<int> NSO_Mother { get; set; }
        public Nullable<int> NSO_Father { get; set; }
        public Nullable<int> Marriage_Contract { get; set; }
        public string dependents { get; set; }
        public Nullable<int> NSO_child1 { get; set; }
        public Nullable<int> NSO_child2 { get; set; }
        public Nullable<int> NSO_child3 { get; set; }
        public string marital_Status { get; set; }
        public Nullable<int> complete { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
